// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfE-GhIHiHvInXCndLNmp5XRAFqsF7mOk',
    appId: '1:497694741433:web:4f3526970a63a53b481c68',
    messagingSenderId: '497694741433',
    projectId: 'projeto-pi-1c9e3',
    authDomain: 'projeto-pi-1c9e3.firebaseapp.com',
    storageBucket: 'projeto-pi-1c9e3.firebasestorage.app',
    measurementId: 'G-L0PPV81BYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jZeIxMq_eaoDZFv5pURkKyePLCci1oY',
    appId: '1:497694741433:android:6a003b91d2680d70481c68',
    messagingSenderId: '497694741433',
    projectId: 'projeto-pi-1c9e3',
    storageBucket: 'projeto-pi-1c9e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJzrSwUoXFx8PYSnqwFFyiih2_MSB1ecg',
    appId: '1:497694741433:ios:68fb201892ccb728481c68',
    messagingSenderId: '497694741433',
    projectId: 'projeto-pi-1c9e3',
    storageBucket: 'projeto-pi-1c9e3.firebasestorage.app',
    iosBundleId: 'com.projeto.pi.projetoObras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJzrSwUoXFx8PYSnqwFFyiih2_MSB1ecg',
    appId: '1:497694741433:ios:68fb201892ccb728481c68',
    messagingSenderId: '497694741433',
    projectId: 'projeto-pi-1c9e3',
    storageBucket: 'projeto-pi-1c9e3.firebasestorage.app',
    iosBundleId: 'com.projeto.pi.projetoObras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfE-GhIHiHvInXCndLNmp5XRAFqsF7mOk',
    appId: '1:497694741433:web:06b83f56f3fd2ba5481c68',
    messagingSenderId: '497694741433',
    projectId: 'projeto-pi-1c9e3',
    authDomain: 'projeto-pi-1c9e3.firebaseapp.com',
    storageBucket: 'projeto-pi-1c9e3.firebasestorage.app',
    measurementId: 'G-685CP79NBP',
  );

}